name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello from GitHub Actions!"

      - name: Show the date
        run: date

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Print Date
        run:  date
