name: Github Actions

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - newbranch

jobs:
  action-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: print index.html file
        run: cat index.html
